import React from 'react'

export default function data_section() {
  return (
    <div>
         {/* Second Data Section (Table) */}
         <div className="bg-white p-8 rounded-xl shadow-lg col-span-1 lg:col-span-2 xl:col-span-1">
            <h2 className="text-xl font-semibold text-gray-700 mb-4">Recent Reports</h2>
            <table className="min-w-full text-left text-sm text-gray-500">
              <thead>
                <tr>
                  <th className="px-6 py-3 font-medium text-gray-700">Report ID</th>
                  <th className="px-6 py-3 font-medium text-gray-700">Generated By</th>
                  <th className="px-6 py-3 font-medium text-gray-700">Date</th>
                  <th className="px-6 py-3 font-medium text-gray-700">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-t">
                  <td className="px-6 py-4">#12345</td>
                  <td className="px-6 py-4">John Doe</td>
                  <td className="px-6 py-4">2024-11-20</td>
                  <td className="px-6 py-4">
                    <button className="text-blue-600 hover:underline">View</button>
                  </td>
                </tr>
                <tr className="border-t">
                  <td className="px-6 py-4">#12346</td>
                  <td className="px-6 py-4">Jane Smith</td>
                  <td className="px-6 py-4">2024-11-19</td>
                  <td className="px-6 py-4">
                    <button className="text-blue-600 hover:underline">View</button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
    </div>
  )
}
